[tool.black]
line-length = 88
target-version = ['py311']


# black \path --diff --color
# to see the changes that black would make

# black \path
# to apply the changes

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

# isort \path
# sort the imports

[tool.autoflake]
check_diff = true
imports = ["sqlalchemy", "API_Learn"]

# autoflake \path
# to remove unused imports